theme = "onedark"

[editor]
line-number = "relative" # it's popular :P
scrolloff = 999 # to keep the cursor centred
mouse = false # mice are for nerds
soft-wrap.enable = true # soft wrap looks nice

[editor.cursor-shape]
insert = "bar"
normal = "block"
select = "underline"
